'use client';

import React from 'react';
import { notFound } from 'next/navigation';
import Link from 'next/link';
import { ArrowRight, CheckCircle, Globe, Megaphone, Bot, Mail, Search, User, Briefcase, Facebook } from 'lucide-react';

// --- Content Configuration ---
const SERVICE_DATA = {
  website: {
    title: "AI-Powered Website Generation",
    description: "Go from a simple idea to a fully functional, professionally designed website in minutes. Our AI understands your goals and builds a site optimized for leads, sales, and engagement.",
    icon: Globe,
    features: [
      "Intelligent sitemap and page structure generation",
      "Professionally written, SEO-friendly copy",
      "Conversion-optimized layouts (for leads, calls, etc.)",
      "Automated branding and style customization",
      "Mobile-perfect, responsive design out-of-the-box"
    ],
    cta: "Build Your Website",
    href: "/builder"
  },
  'sms-campaign': {
    title: "High-Impact SMS Campaigns",
    description: "Launch targeted SMS campaigns that get delivered and read. Perfect for promotions, announcements, and re-engaging your audience with near-instant impact.",
    icon: Megaphone,
    features: [
      "AI-generated campaign copy and angles",
      "Audience segmentation and targeting",
      "Link tracking and performance analytics",
      "Compliance and opt-out management",
      "Direct integration with your contact lists"
    ],
    cta: "Launch an SMS Campaign",
    href: "/products/sms-marketing"
  },
  'ai-market-expert': {
    title: "Your AI Market Expert",
    description: "Get real-time data, insights, and strategic advice on any market. Our AI expert analyzes trends, competitors, and opportunities to give you a decisive edge.",
    icon: Bot,
    features: [
        "Real-time market trend analysis",
        "Competitor strategy breakdowns",
        "Audience demographic and psychographic insights",
        "Data-driven growth opportunities",
        "Actionable reports and summaries"
    ],
    cta: "Consult the AI Expert",
    href: "/discover"
  },
  'email-campaign': {
    title: "Automated Email Marketing",
    description: "Design, write, and schedule hyper-personalized email sequences that nurture leads and drive sales on autopilot.",
    icon: Mail,
    features: [
        "AI-powered copy and subject line generation",
        "Beautiful, responsive email templates",
        "Automated drip campaigns for lead nurturing",
        "Integration with your CRM or contact lists",
        "Advanced open and click-through analytics"
    ],
    cta: "Create Email Campaign",
    href: "/products/email-marketing"
  },
  'google-ads': {
    title: "Google Ads Automation",
    description: "Launch high-ROI Google Search campaigns in minutes. Our AI handles the keywords, ad copy, and bidding strategy.",
    icon: Search,
    features: [
        "Automated keyword research and selection",
        "High-converting ad copy generated by AI",
        "Intelligent budget allocation and bid management",
        "Real-time performance dashboard",
        "No complex Google Ads account setup needed"
    ],
    cta: "Launch Google Ads",
    href: "/products/google-ads"
  },
  'meta-lead-gen': {
    title: "Meta (Facebook & Instagram) Ads",
    description: "Generate a steady stream of qualified leads from Facebook and Instagram with AI-optimized campaigns.",
    icon: Facebook,
    features: [
        "AI-powered audience targeting and creative generation",
        "Seamless lead form integration",
        "Direct connection to your CRM or spreadsheet",
        "Performance analytics and cost-per-lead tracking",
        "Automated comment replies to capture interest"
    ],
    cta: "Start Meta Campaign",
    href: "/products/instagram-bot" // Redirects to a related product page for now
  },
};

interface PageProps {
  params: { service: string };
  searchParams: { [key: string]: string | string[] | undefined };
}

// --- Page Component ---
export default function ServicePage({ params }: PageProps) {
  const serviceKey = params.service as keyof typeof SERVICE_DATA;
  const service = SERVICE_DATA[serviceKey];

  // If the service doesn't exist, show a 404 page.
  if (!service) {
    notFound();
  }

  const Icon = service.icon;

  return (
    <div className="min-h-screen bg-zinc-950 text-white flex flex-col items-center justify-center p-4 sm:p-8">
      <div className="w-full max-w-4xl">
        {/* Header */}
        <div className="text-center mb-12">
          <div className="inline-block bg-blue-900/50 p-4 rounded-full mb-6 border border-blue-700">
            <Icon className="h-10 w-10 text-blue-300" />
          </div>
          <h1 className="text-4xl md:text-6xl font-bold tracking-tight bg-clip-text text-transparent bg-gradient-to-b from-white to-zinc-300 mb-4">{service.title}</h1>
          <p className="text-lg md:text-xl text-zinc-400 max-w-3xl mx-auto">{service.description}</p>
        </div>

        {/* Features & CTA */}
        <div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-8 md:p-12">
          <div className="grid md:grid-cols-2 gap-8 items-center">
            <div className="space-y-4">
              <h2 className="text-2xl font-semibold mb-4">Key Features</h2>
              <ul className="space-y-3">
                {service.features.map((feature, i) => (
                  <li key={i} className="flex items-start">
                    <CheckCircle className="h-6 w-6 text-green-500 mr-3 mt-1 flex-shrink-0" />
                    <span className="text-zinc-300">{feature}</span>
                  </li>
                ))}
              </ul>
            </div>
            <div className="bg-zinc-800/50 p-8 rounded-lg text-center flex flex-col items-center justify-center h-full border border-zinc-700">
              <h3 className="text-2xl font-bold mb-4">Ready to Start?</h3>
              <p className="text-zinc-400 mb-6">Begin the guided process. It only takes a minute.</p>
              <Link href={service.href} passHref>
                <button className="w-full bg-blue-600 text-white font-bold py-3 px-6 rounded-lg text-lg hover:bg-blue-700 transition-all duration-300 transform hover:scale-105 flex items-center justify-center shadow-lg shadow-blue-900/50">
                  {service.cta} <ArrowRight className="ml-2 h-5 w-5" />
                </button>
              </Link>
            </div>
          </div>
        </div>
        
         <div className="text-center mt-12">
            <Link href="/" passHref>
                <span className="text-zinc-500 hover:text-white transition-colors">Browse other services</span>
            </Link>
        </div>
      </div>
    </div>
  );
}
